version: "3"

services:
  nginx:
    build: ./requirements/nginx/
    image: nginx:inception
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306"
    networks:
      - my_network
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000"
    networks:
      - my_network
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/najlio/data/wordpress_data
  mariadb_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/najlio/data/mariadb_data

networks:
  my_network:
    name: my_network
    driver: bridge