FROM debian:bullseye

# Install required packages
RUN apt-get update && \
    apt-get install -y \
        php7.4 \
        php-fpm \
        php-mysql \
        curl \
        wget \
        unzip \
        mariadb-client


RUN mkdir -p /var/www/html
RUN mkdir -p /run/php

# Download and extract WordPress
# RUN wget -q -O /tmp/wordpress.tar.gz https://wordpress.org/latest.tar.gz && \
#     tar -xzf /tmp/wordpress.tar.gz -C /var/www/html --strip-components=1 && \
#     rm /tmp/wordpress.tar.gz

# Set ownership and permissions
RUN chown -R www-data:www-data /var/www/* 

# Configure php-fpm
COPY conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

# Install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY ./tools/ /tmp/
RUN chmod +x /tmp/init_wordpress.sh

# Start php-fpm
CMD ["/tmp/init_wordpress.sh"]