FROM debian:bullseye

RUN apt update -y && apt upgrade -y
RUN apt install nginx -y && apt install openssl -y

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key \
    -subj "/CN=nloutfi.42.fr"

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./tools/index.html /var/www/html/index.html

ENTRYPOINT ["nginx", "-g", "daemon off;"]